"""
PDF renderer for Suspicious Transaction Report (STR).
"""

from __future__ import annotations

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os


def render_pdf(
    entity_id: str,
    risk_score: float,
    tier: str,
    reasons: list[str],
    str_text: str,
    output_path: str = "reports"
) -> str:
    """
    Generate a formatted STR PDF.

    Returns:
        Path to generated PDF file
    """

    # -----------------------------
    # Create output directory
    # -----------------------------
    os.makedirs(output_path, exist_ok=True)

    filename = f"{output_path}/STR_{entity_id}_{int(datetime.now().timestamp())}.pdf"

    # -----------------------------
    # Create document
    # -----------------------------
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()

    elements = []

    # -----------------------------
    # Title
    # -----------------------------
    elements.append(Paragraph("<b>Suspicious Transaction Report (STR)</b>", styles["Title"]))
    elements.append(Spacer(1, 20))

    # -----------------------------
    # Metadata
    # -----------------------------
    elements.append(Paragraph(f"<b>Entity ID:</b> {entity_id}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Risk Score:</b> {risk_score:.2f}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Risk Tier:</b> {tier}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Generated At:</b> {datetime.utcnow().isoformat()} UTC", styles["Normal"]))
    elements.append(Spacer(1, 20))

    # -----------------------------
    # Reasons
    # -----------------------------
    elements.append(Paragraph("<b>Key Risk Factors:</b>", styles["Heading2"]))
    for r in reasons:
        elements.append(Paragraph(f"- {r}", styles["Normal"]))

    elements.append(Spacer(1, 20))

    # -----------------------------
    # STR Narrative (Gemini output)
    # -----------------------------
    elements.append(Paragraph("<b>Investigation Summary:</b>", styles["Heading2"]))
    elements.append(Spacer(1, 10))

    # Break long text into chunks
    for line in str_text.split("\n"):
        elements.append(Paragraph(line, styles["Normal"]))

    elements.append(Spacer(1, 20))

    # -----------------------------
    # Footer
    # -----------------------------
    elements.append(Paragraph(
        "<i>This report is auto-generated by Cyphron AI Detection System.</i>",
        styles["Italic"]
    ))

    # -----------------------------
    # Build PDF
    # -----------------------------
    doc.build(elements)

    print(f"📄 PDF generated: {filename}")

    return filename