import type { PDFFont, PDFPage } from "pdf-lib";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 50;
const LINE = 14;
const CONTENT_W = PAGE_W - 2 * MARGIN;

function wrapLine(text: string, font: PDFFont, size: number, maxW: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const w of words) {
    const next = current ? `${current} ${w}` : w;
    if (font.widthOfTextAtSize(next, size) <= maxW) {
      current = next;
    } else {
      if (current) lines.push(current);
      if (font.widthOfTextAtSize(w, size) > maxW) {
        let chunk = "";
        for (const ch of w) {
          const t = chunk + ch;
          if (font.widthOfTextAtSize(t, size) <= maxW) chunk = t;
          else {
            if (chunk) lines.push(chunk);
            chunk = ch;
          }
        }
        current = chunk;
      } else {
        current = w;
      }
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

/** PDF aligned with pipeline `pdf_renderer.render_pdf` section order (+ Cyphron header). */
export async function buildStrReportPdfBytes(params: {
  entityId: string;
  riskScore: number;
  tier: string;
  reasons: string[];
  strText: string;
  generatedAt: string;
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page: PDFPage = doc.addPage([PAGE_W, PAGE_H]);
  /** Baseline Y (pdf-lib: origin bottom-left). */
  let y = PAGE_H - 55;

  const needSpace = (lines: number) => {
    const need = lines * LINE;
    if (y - need < MARGIN + 28) {
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - 55;
    }
  };

  const drawRaw = (text: string, size: number, bold: boolean) => {
    const f = bold ? fontBold : font;
    for (const line of wrapLine(text.replace(/[\r\n]+/g, " "), f, size, CONTENT_W)) {
      needSpace(1);
      page.drawText(line, {
        x: MARGIN,
        y,
        size,
        font: f,
        color: rgb(0.12, 0.12, 0.12),
      });
      y -= LINE;
    }
  };

  const drawParagraph = (text: string, size = 10) => {
    const blocks = text.split("\n");
    for (const raw of blocks) {
      if (!raw.trim()) {
        needSpace(1);
        y -= LINE * 0.35;
        continue;
      }
      for (const wline of wrapLine(raw, font, size, CONTENT_W)) {
        needSpace(1);
        page.drawText(wline, {
          x: MARGIN,
          y,
          size,
          font,
          color: rgb(0.15, 0.15, 0.15),
        });
        y -= LINE;
      }
    }
  };

  drawRaw("Cyphron", 10, true);
  drawRaw("Suspicious Transaction Report (STR)", 14, true);
  y -= 4;
  drawRaw(`Entity ID: ${params.entityId}`, 10, false);
  drawRaw(`Risk Score: ${params.riskScore.toFixed(4)}`, 10, false);
  drawRaw(`Risk Tier: ${params.tier}`, 10, false);
  drawRaw(`Generated At: ${params.generatedAt}`, 10, false);
  y -= 6;
  drawRaw("Key Risk Factors:", 11, true);
  for (const r of params.reasons) {
    drawRaw(`- ${r}`, 10, false);
  }
  y -= 6;
  drawRaw("Investigation Summary:", 11, true);
  y -= 2;
  drawParagraph(params.strText, 10);
  y -= 8;
  drawRaw("This report is auto-generated by Cyphron AI Detection System.", 9, false);

  return doc.save();
}

export function sanitizePdfFilenamePart(id: string): string {
  return id.replace(/[^a-zA-Z0-9._-]+/g, "_").slice(0, 80) || "report";
}
